#!/usr/bin/env zsh
# do-here-now-migrator — phase 11: report.
#
# Writes a migration record into the repository. Six months later the only
# thing anyone remembers is that "the site moved"; this file is what answers
# what was destroyed, what was kept, where the backups are, and what still
# needs a human.

dhm_report_status_line() {  # dhm_report_status_line <site> <phase>
  local phase_status; phase_status=$(dhm_phase_status "$1" "$2")
  case "$phase_status" in
    done)    print -r -- "done" ;;
    failed)  print -r -- "FAILED" ;;
    skipped) print -r -- "skipped" ;;
    *)       print -r -- "pending" ;;
  esac
}

dhm_report_print() {  # dhm_report_print <site>
  local site=$1 p
  print -r -- ""
  print -r -- "${DHM_C_BOLD}migration: ${site}${DHM_C_RESET}"
  print -r -- ""
  for p in "${DHM_PHASES[@]}"; do
    printf '  %-14s %s\n' "$p" "$(dhm_report_status_line "$site" "$p")"
  done
  print -r -- ""
  local domain slug url backup
  domain=$(dhm_fact_get "$site" domain)
  slug=$(dhm_fact_get "$site" slug)
  url=$(dhm_fact_get "$site" site_url)
  backup=$(dhm_fact_get "$site" backup_dir)
  [[ -n "$domain" ]] && print -r -- "  domain      https://${domain}"
  [[ -n "$slug" ]]   && print -r -- "  here.now    ${url:-https://${slug}.here.now/}  (slug ${slug})"
  [[ -n "$backup" ]] && print -r -- "  backups     ${backup}"
  print -r -- "  state       $(dhm_state_file "$site")"
  print -r -- ""
}

# The durable record, written into the repository under docs/.
dhm_report_write_doc() {  # dhm_report_write_doc <site> <repo> <inventory-json>
  local site=$1 repo=$2 inv=$3 file="${2}/docs/migration-to-here-now.md"

  if dhm_dry "write ${file}"; then return 0; fi
  mkdir -p "${file:h}" || return 1

  local domain slug backup database_backup provider suburl agent
  domain=$(dhm_fact_get "$site" domain)
  slug=$(dhm_fact_get "$site" slug)
  backup=$(dhm_fact_get "$site" backup_dir)
  database_backup=$(dhm_fact_get "$site" database_backup_dir)
  provider=$(dhm_fact_get "$site" subscribe_provider)
  suburl=$(dhm_fact_get "$site" subscribe_url)
  agent=$(dhm_state_get "$site" '.agent')

  {
    print -r -- "# Migration to here.now"
    print -r -- ""
    print -r -- "Generated by \`dhm\` on $(dhm_now_utc). This file records what moved,"
    print -r -- "what remains, and what still needs a human."
    print -r -- ""
    print -r -- "## Result"
    print -r -- ""
    print -r -- "| | |"
    print -r -- "| --- | --- |"
    print -r -- "| Primary domain | \`${domain:-—}\` |"
    print -r -- "| here.now Site | \`${slug:-—}\` (\`https://${slug}.here.now/\`) |"
    print -r -- "| Hosting before | DigitalOcean App Platform |"
    print -r -- "| Hosting after | here.now static Site |"
    print -r -- "| Subscribe provider | ${provider:-none}${suburl:+ — \`${suburl}\`} |"
    print -r -- "| Transform agent | ${agent:-—} |"
    print -r -- ""

    local decommissioned=""
    dhm_phase_is_done "$site" decommission && decommissioned=1
    if [[ -n "$decommissioned" ]]; then
      print -r -- "## Destroyed on DigitalOcean"
    else
      print -r -- "## Pending DigitalOcean decommission"
    fi
    print -r -- ""
    local napps ndbs
    napps=$(jq '.claimed.apps | length' <<<"$inv")
    ndbs=$(jq '.claimed.databases | length' <<<"$inv")
    if (( napps == 0 && ndbs == 0 )); then
      print -r -- "No DigitalOcean resources were attributed to this site."
    else
      print -r -- "| Resource | Type | ID |"
      print -r -- "| --- | --- | --- |"
      jq -r '.claimed.apps[] | "| `\(.name)` | App Platform app | `\(.id)` |"' <<<"$inv"
      jq -r '.claimed.databases[] | "| `\(.name)` | managed \(.engine) | `\(.id)` |"' <<<"$inv"
    fi
    print -r -- ""
    if [[ -n "$decommissioned" ]]; then
      print -r -- "The attributed resources above were removed only after production verification."
    elif (( napps > 0 )); then
      print -r -- "The attributed app remains active at its default DigitalOcean ingress as a rollback fallback."
      print -r -- "Its custom domain is detached; deleting it still requires the separate, exact-name-confirmed"
      print -r -- "\`dhm decommission --site ${site}\` command."
    elif (( ndbs > 0 )); then
      print -r -- "The attributed database remains active until the separate, exact-name-confirmed"
      print -r -- "decommission command removes it."
    fi
    print -r -- ""

    print -r -- "## Retained"
    print -r -- ""
    print -r -- "- DNS zones stay with the existing provider. Only apex and \`www\`"
    print -r -- "  \`A\`/\`AAAA\`/\`CNAME\` records were rewritten."
    print -r -- "- All \`MX\`, \`TXT\`, \`SPF\`, \`DKIM\`, \`DMARC\`, \`CAA\`, and \`SRV\` records were"
    print -r -- "  preserved untouched, so email is unaffected."
    jq -r '.untouched.apps[]? | "- App `\(.name)` — unrelated, left running."' <<<"$inv"
    jq -r '.untouched.databases[]? | "- Database `\(.name)` (\(.engine)) — unrelated, left running."' <<<"$inv"
    print -r -- ""

    print -r -- "## Backups"
    print -r -- ""
    print -r -- "\`${backup:-—}\` — a sibling of this checkout, outside version control."
    if [[ -n "$database_backup" ]]; then
      print -r -- ""
      print -r -- "Final database backup: \`${database_backup}\`."
    fi
    print -r -- ""
    print -r -- "| File | Contents |"
    print -r -- "| --- | --- |"
    print -r -- "| \`*/\*.bson\`, \`*.pgcustom\`, \`dump.sql\` | database dumps, restorable with the engine's native tool |"
    print -r -- "| \`*/subscribers-import.csv\` | \`email,name,created_at\` — the shape newsletter platforms import |"
    print -r -- "| \`app-specs/*.yaml\` | archived App Platform specs (mode 600, secret-bearing) |"
    print -r -- "| \`dns/*.json\` | pre-migration DNS records, for rollback |"
    print -r -- "| \`manifest.json\` | the full inventory this migration acted on |"
    print -r -- ""

    print -r -- "## Deployment"
    print -r -- ""
    print -r -- "Pushing to \`main\` runs \`.github/workflows/deploy-here-now.yml\`, which"
    print -r -- "builds the static export and publishes it to Site \`${slug:-<slug>}\`."
    print -r -- ""
    print -r -- "It requires two repository settings:"
    print -r -- ""
    print -r -- "- secret \`HERENOW_API_KEY\`"
    print -r -- "- variable \`HERENOW_SLUG\` = \`${slug:-<slug>}\`"
    print -r -- ""

    print -r -- "## Rollback"
    print -r -- ""
    if [[ -n "$decommissioned" && napps -gt 0 ]]; then
      print -r -- "The DigitalOcean origin has been destroyed, so recovery means re-publishing"
      print -r -- "a known-good export to the same slug:"
    elif [[ -n "$decommissioned" && ndbs -gt 0 ]]; then
      print -r -- "The DigitalOcean database has been destroyed; it was not a web origin."
      print -r -- "The site recovery path is re-publishing a known-good export to the same slug:"
    elif [[ -n "$decommissioned" ]]; then
      print -r -- "The site recovery path is re-publishing a known-good export to the same slug:"
    elif (( napps > 0 )); then
      print -r -- "The DigitalOcean app remains available at its default ingress until decommissioned."
      print -r -- "The primary recovery path is still re-publishing a known-good export to the same slug:"
    elif (( ndbs > 0 )); then
      print -r -- "The DigitalOcean database remains available until decommissioned, but it is not a web origin."
      print -r -- "The site recovery path is re-publishing a known-good export to the same slug:"
    else
      print -r -- "The site recovery path is re-publishing a known-good export to the same slug:"
    fi
    print -r -- ""
    print -r -- '```zsh'
    print -r -- "\$HOME/.agents/skills/here-now/scripts/publish.sh <output-dir> --slug ${slug:-<slug>}"
    print -r -- '```'
    print -r -- ""
    print -r -- "Pre-migration DNS records are in \`${backup:-<backup>}/dns/\` if the zone"
    print -r -- "itself needs restoring."
    print -r -- ""

    print -r -- "## Known limits"
    print -r -- ""
    print -r -- "- The here.now Free plan allows **one** custom domain. A second domain"
    print -r -- "  needs a paid plan; DNS alone cannot HTTP-redirect one domain to another."
    print -r -- "- A static site has no runtime. Anything that needed a server — auth,"
    print -r -- "  form POSTs, scheduled jobs, API routes — is gone, not moved."
  } > "$file"

  dhm_ok "wrote ${file}"
  print -r -- "$file"
}
